### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [kerolasa/f5gs#2]
Would you like to add the configuration script "[AX_PTHREAD](http://www.gnu.org/software/autoconf-archive/ax_pthread.html "How to build C programs using POSIX threads?")" to [your build specification](https://github.com/kerolasa/f5gs/blob/c705638e48d9ed12c4f35a2af966f94e9b282770/configure.ac#L37 "Configuration checks")?

**Comment by kerolasa** [comment]
Hi Markus,

Sorry. I rarely look github messages, and I should add to the README note about that.

Anyway, the AX_PTHREAD is not needed. The gnulib pthread should do the job.

https://github.com/kerolasa/f5gs/blob/master/bootstrap.conf#L37

**Comment by elfring** [comment]
I would recommend to reuse known configuration checks in [your build specification](https://github.com/kerolasa/f5gs/blob/6955f63938be2dd109c4f5820fd542876870cc40/configure.ac#L37 "System checks").
