### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [kerolasa/f5gs#3]
The function "[pthread_rwlock_destroy](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_rwlock_destroy.html "Destroy a read-write lock object")" does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/seccode/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers "Call only asynchronous-safe functions within signal handlers.").
I guess that a different program design will be needed for your function "[stop_server](https://github.com/kerolasa/f5gs/blob/05ca8721d3678cad8085468b4e7979725c2ef87d/f5gs.c#L403 "Reconsider signal handling implementation")".

**Comment by kerolasa** [comment]
Fixed in.

https://github.com/kerolasa/f5gs/commit/05f471a81c5dce1520ff1b9fadaa994f7127351b

**Comment by elfring** [comment]
Thanks for your small source code improvement.
