### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [kerolasa/f5gs#4]
Would you like to add more error handling for return values from functions like the following?
- [fputs](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fputs.html "Put a string on a stream") ⇒ [usage](https://github.com/kerolasa/f5gs/blob/05ca8721d3678cad8085468b4e7979725c2ef87d/f5gs.c#L87)
- [pthread_create](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_create.html "Thread creation") ⇒ [run_server](https://github.com/kerolasa/f5gs/blob/05ca8721d3678cad8085468b4e7979725c2ef87d/f5gs.c#L426)

**Comment by kerolasa** [comment]
The usage() error handling is done with atexit(close_stdout);

The run_server() issue is corrected in.
https://github.com/kerolasa/f5gs/commit/d2cda63be1ed20b4061a45e9761998b71b0e347b

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.
- [pthread_rwlock_rdlock](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_create.html "Lock a read-write lock object for reading") ⇒ [handle_request](https://github.com/kerolasa/f5gs/blob/d2cda63be1ed20b4061a45e9761998b71b0e347b/f5gs.c#L152)
- [sigaction](http://pubs.opengroup.org/onlinepubs/9699919799/functions/signal.html "Change a signal action") ⇒ [run_server](https://github.com/kerolasa/f5gs/blob/d2cda63be1ed20b4061a45e9761998b71b0e347b/f5gs.c#L503)

Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by kerolasa** [comment]
> Are you interested to apply aspect-oriented software development?

I can review patches if you send some.

**Comment by elfring** [comment]
Are you willing to [integrate a tool like AspectC++](http://aspectc.org/ "Reuse of AspectC++?") into your software development process?
