### ISSUE TITLE
Reconsider service architecture?

### ISSUE THREAD

**Issue by elfring** [kerolasa/f5gs#5]
[The current software](https://github.com/kerolasa/f5gs/blob/05ca8721d3678cad8085468b4e7979725c2ef87d/f5gs.c#L426 "Connection handling") implements [the strategy "Thread per Request"](http://lycog.com/distributed-systems/thread-per-request/ "multi-threading"). This approach can become inappropriate with increasing usage requirements.

Would you like to [consider also different service designs](http://kegel.com/c10k.html "The C10K problem")?

**Comment by kerolasa** [comment]
I have used the software successfully in production environment with the current 'design' so this is not fatal flaw, but to be honest the 'design' gives unarguably Bad Vibes(TM). I try come up with something better.

**Comment by elfring** [comment]
Would you like to introduce [a connection and thread pool](https://en.wikipedia.org/wiki/Thread_pool_pattern "Reuse of thread pools?") for example with the next try?

**Comment by kerolasa** [comment]
The commit below is good enough. Please send a patch (by email) if you want to change that to something else.

f72ca547092d7d650f27f8e4bd024b5abc2cf582
